export type ElementCategory =
  | "alkali metal"
  | "alkaline earth metal"
  | "transition metal"
  | "post-transition metal"
  | "metalloid"
  | "reactive nonmetal"
  | "noble gas"
  | "lanthanide"
  | "actinide";

export type PeriodicElement = {
  atomicNumber: number;
  symbol: string;
  name: string;
  molarMass: number;
  category: ElementCategory;
  period: number;
  group: number;
};

export const periodicElements: PeriodicElement[] = [
  { atomicNumber: 1, symbol: "H", name: "Hydrogen", molarMass: 1.008, category: "reactive nonmetal", period: 1, group: 1 },
  { atomicNumber: 2, symbol: "He", name: "Helium", molarMass: 4.003, category: "noble gas", period: 1, group: 18 },
  { atomicNumber: 3, symbol: "Li", name: "Lithium", molarMass: 6.94, category: "alkali metal", period: 2, group: 1 },
  { atomicNumber: 4, symbol: "Be", name: "Beryllium", molarMass: 9.012, category: "alkaline earth metal", period: 2, group: 2 },
  { atomicNumber: 5, symbol: "B", name: "Boron", molarMass: 10.81, category: "metalloid", period: 2, group: 13 },
  { atomicNumber: 6, symbol: "C", name: "Carbon", molarMass: 12.011, category: "reactive nonmetal", period: 2, group: 14 },
  { atomicNumber: 7, symbol: "N", name: "Nitrogen", molarMass: 14.007, category: "reactive nonmetal", period: 2, group: 15 },
  { atomicNumber: 8, symbol: "O", name: "Oxygen", molarMass: 15.999, category: "reactive nonmetal", period: 2, group: 16 },
  { atomicNumber: 9, symbol: "F", name: "Fluorine", molarMass: 18.998, category: "reactive nonmetal", period: 2, group: 17 },
  { atomicNumber: 10, symbol: "Ne", name: "Neon", molarMass: 20.18, category: "noble gas", period: 2, group: 18 },
  { atomicNumber: 11, symbol: "Na", name: "Sodium", molarMass: 22.99, category: "alkali metal", period: 3, group: 1 },
  { atomicNumber: 12, symbol: "Mg", name: "Magnesium", molarMass: 24.305, category: "alkaline earth metal", period: 3, group: 2 },
  { atomicNumber: 13, symbol: "Al", name: "Aluminum", molarMass: 26.982, category: "post-transition metal", period: 3, group: 13 },
  { atomicNumber: 14, symbol: "Si", name: "Silicon", molarMass: 28.085, category: "metalloid", period: 3, group: 14 },
  { atomicNumber: 15, symbol: "P", name: "Phosphorus", molarMass: 30.974, category: "reactive nonmetal", period: 3, group: 15 },
  { atomicNumber: 16, symbol: "S", name: "Sulfur", molarMass: 32.06, category: "reactive nonmetal", period: 3, group: 16 },
  { atomicNumber: 17, symbol: "Cl", name: "Chlorine", molarMass: 35.45, category: "reactive nonmetal", period: 3, group: 17 },
  { atomicNumber: 18, symbol: "Ar", name: "Argon", molarMass: 39.948, category: "noble gas", period: 3, group: 18 },
  { atomicNumber: 19, symbol: "K", name: "Potassium", molarMass: 39.098, category: "alkali metal", period: 4, group: 1 },
  { atomicNumber: 20, symbol: "Ca", name: "Calcium", molarMass: 40.078, category: "alkaline earth metal", period: 4, group: 2 },
  { atomicNumber: 21, symbol: "Sc", name: "Scandium", molarMass: 44.956, category: "transition metal", period: 4, group: 3 },
  { atomicNumber: 22, symbol: "Ti", name: "Titanium", molarMass: 47.867, category: "transition metal", period: 4, group: 4 },
  { atomicNumber: 23, symbol: "V", name: "Vanadium", molarMass: 50.942, category: "transition metal", period: 4, group: 5 },
  { atomicNumber: 24, symbol: "Cr", name: "Chromium", molarMass: 51.996, category: "transition metal", period: 4, group: 6 },
  { atomicNumber: 25, symbol: "Mn", name: "Manganese", molarMass: 54.938, category: "transition metal", period: 4, group: 7 },
  { atomicNumber: 26, symbol: "Fe", name: "Iron", molarMass: 55.845, category: "transition metal", period: 4, group: 8 },
  { atomicNumber: 27, symbol: "Co", name: "Cobalt", molarMass: 58.933, category: "transition metal", period: 4, group: 9 },
  { atomicNumber: 28, symbol: "Ni", name: "Nickel", molarMass: 58.693, category: "transition metal", period: 4, group: 10 },
  { atomicNumber: 29, symbol: "Cu", name: "Copper", molarMass: 63.546, category: "transition metal", period: 4, group: 11 },
  { atomicNumber: 30, symbol: "Zn", name: "Zinc", molarMass: 65.38, category: "transition metal", period: 4, group: 12 },
  { atomicNumber: 31, symbol: "Ga", name: "Gallium", molarMass: 69.723, category: "post-transition metal", period: 4, group: 13 },
  { atomicNumber: 32, symbol: "Ge", name: "Germanium", molarMass: 72.63, category: "metalloid", period: 4, group: 14 },
  { atomicNumber: 33, symbol: "As", name: "Arsenic", molarMass: 74.922, category: "metalloid", period: 4, group: 15 },
  { atomicNumber: 34, symbol: "Se", name: "Selenium", molarMass: 78.971, category: "reactive nonmetal", period: 4, group: 16 },
  { atomicNumber: 35, symbol: "Br", name: "Bromine", molarMass: 79.904, category: "reactive nonmetal", period: 4, group: 17 },
  { atomicNumber: 36, symbol: "Kr", name: "Krypton", molarMass: 83.798, category: "noble gas", period: 4, group: 18 },
  { atomicNumber: 37, symbol: "Rb", name: "Rubidium", molarMass: 85.468, category: "alkali metal", period: 5, group: 1 },
  { atomicNumber: 38, symbol: "Sr", name: "Strontium", molarMass: 87.62, category: "alkaline earth metal", period: 5, group: 2 },
  { atomicNumber: 39, symbol: "Y", name: "Yttrium", molarMass: 88.906, category: "transition metal", period: 5, group: 3 },
  { atomicNumber: 40, symbol: "Zr", name: "Zirconium", molarMass: 91.224, category: "transition metal", period: 5, group: 4 },
  { atomicNumber: 41, symbol: "Nb", name: "Niobium", molarMass: 92.906, category: "transition metal", period: 5, group: 5 },
  { atomicNumber: 42, symbol: "Mo", name: "Molybdenum", molarMass: 95.95, category: "transition metal", period: 5, group: 6 },
  { atomicNumber: 43, symbol: "Tc", name: "Technetium", molarMass: 98, category: "transition metal", period: 5, group: 7 },
  { atomicNumber: 44, symbol: "Ru", name: "Ruthenium", molarMass: 101.07, category: "transition metal", period: 5, group: 8 },
  { atomicNumber: 45, symbol: "Rh", name: "Rhodium", molarMass: 102.91, category: "transition metal", period: 5, group: 9 },
  { atomicNumber: 46, symbol: "Pd", name: "Palladium", molarMass: 106.42, category: "transition metal", period: 5, group: 10 },
  { atomicNumber: 47, symbol: "Ag", name: "Silver", molarMass: 107.868, category: "transition metal", period: 5, group: 11 },
  { atomicNumber: 48, symbol: "Cd", name: "Cadmium", molarMass: 112.414, category: "transition metal", period: 5, group: 12 },
  { atomicNumber: 49, symbol: "In", name: "Indium", molarMass: 114.818, category: "post-transition metal", period: 5, group: 13 },
  { atomicNumber: 50, symbol: "Sn", name: "Tin", molarMass: 118.71, category: "post-transition metal", period: 5, group: 14 },
  { atomicNumber: 51, symbol: "Sb", name: "Antimony", molarMass: 121.76, category: "metalloid", period: 5, group: 15 },
  { atomicNumber: 52, symbol: "Te", name: "Tellurium", molarMass: 127.6, category: "metalloid", period: 5, group: 16 },
  { atomicNumber: 53, symbol: "I", name: "Iodine", molarMass: 126.904, category: "reactive nonmetal", period: 5, group: 17 },
  { atomicNumber: 54, symbol: "Xe", name: "Xenon", molarMass: 131.293, category: "noble gas", period: 5, group: 18 },
  { atomicNumber: 55, symbol: "Cs", name: "Cesium", molarMass: 132.905, category: "alkali metal", period: 6, group: 1 },
  { atomicNumber: 56, symbol: "Ba", name: "Barium", molarMass: 137.327, category: "alkaline earth metal", period: 6, group: 2 },
  { atomicNumber: 57, symbol: "La", name: "Lanthanum", molarMass: 138.905, category: "lanthanide", period: 8, group: 4 },
  { atomicNumber: 58, symbol: "Ce", name: "Cerium", molarMass: 140.116, category: "lanthanide", period: 8, group: 5 },
  { atomicNumber: 59, symbol: "Pr", name: "Praseodymium", molarMass: 140.908, category: "lanthanide", period: 8, group: 6 },
  { atomicNumber: 60, symbol: "Nd", name: "Neodymium", molarMass: 144.242, category: "lanthanide", period: 8, group: 7 },
  { atomicNumber: 61, symbol: "Pm", name: "Promethium", molarMass: 145, category: "lanthanide", period: 8, group: 8 },
  { atomicNumber: 62, symbol: "Sm", name: "Samarium", molarMass: 150.36, category: "lanthanide", period: 8, group: 9 },
  { atomicNumber: 63, symbol: "Eu", name: "Europium", molarMass: 151.964, category: "lanthanide", period: 8, group: 10 },
  { atomicNumber: 64, symbol: "Gd", name: "Gadolinium", molarMass: 157.25, category: "lanthanide", period: 8, group: 11 },
  { atomicNumber: 65, symbol: "Tb", name: "Terbium", molarMass: 158.925, category: "lanthanide", period: 8, group: 12 },
  { atomicNumber: 66, symbol: "Dy", name: "Dysprosium", molarMass: 162.5, category: "lanthanide", period: 8, group: 13 },
  { atomicNumber: 67, symbol: "Ho", name: "Holmium", molarMass: 164.93, category: "lanthanide", period: 8, group: 14 },
  { atomicNumber: 68, symbol: "Er", name: "Erbium", molarMass: 167.259, category: "lanthanide", period: 8, group: 15 },
  { atomicNumber: 69, symbol: "Tm", name: "Thulium", molarMass: 168.934, category: "lanthanide", period: 8, group: 16 },
  { atomicNumber: 70, symbol: "Yb", name: "Ytterbium", molarMass: 173.045, category: "lanthanide", period: 8, group: 17 },
  { atomicNumber: 71, symbol: "Lu", name: "Lutetium", molarMass: 174.967, category: "lanthanide", period: 8, group: 18 },
  { atomicNumber: 72, symbol: "Hf", name: "Hafnium", molarMass: 178.49, category: "transition metal", period: 6, group: 4 },
  { atomicNumber: 73, symbol: "Ta", name: "Tantalum", molarMass: 180.948, category: "transition metal", period: 6, group: 5 },
  { atomicNumber: 74, symbol: "W", name: "Tungsten", molarMass: 183.84, category: "transition metal", period: 6, group: 6 },
  { atomicNumber: 75, symbol: "Re", name: "Rhenium", molarMass: 186.207, category: "transition metal", period: 6, group: 7 },
  { atomicNumber: 76, symbol: "Os", name: "Osmium", molarMass: 190.23, category: "transition metal", period: 6, group: 8 },
  { atomicNumber: 77, symbol: "Ir", name: "Iridium", molarMass: 192.217, category: "transition metal", period: 6, group: 9 },
  { atomicNumber: 78, symbol: "Pt", name: "Platinum", molarMass: 195.084, category: "transition metal", period: 6, group: 10 },
  { atomicNumber: 79, symbol: "Au", name: "Gold", molarMass: 196.967, category: "transition metal", period: 6, group: 11 },
  { atomicNumber: 80, symbol: "Hg", name: "Mercury", molarMass: 200.592, category: "transition metal", period: 6, group: 12 },
  { atomicNumber: 81, symbol: "Tl", name: "Thallium", molarMass: 204.38, category: "post-transition metal", period: 6, group: 13 },
  { atomicNumber: 82, symbol: "Pb", name: "Lead", molarMass: 207.2, category: "post-transition metal", period: 6, group: 14 },
  { atomicNumber: 83, symbol: "Bi", name: "Bismuth", molarMass: 208.98, category: "post-transition metal", period: 6, group: 15 },
  { atomicNumber: 84, symbol: "Po", name: "Polonium", molarMass: 209, category: "metalloid", period: 6, group: 16 },
  { atomicNumber: 85, symbol: "At", name: "Astatine", molarMass: 210, category: "metalloid", period: 6, group: 17 },
  { atomicNumber: 86, symbol: "Rn", name: "Radon", molarMass: 222, category: "noble gas", period: 6, group: 18 },
  { atomicNumber: 87, symbol: "Fr", name: "Francium", molarMass: 223, category: "alkali metal", period: 7, group: 1 },
  { atomicNumber: 88, symbol: "Ra", name: "Radium", molarMass: 226, category: "alkaline earth metal", period: 7, group: 2 },
  { atomicNumber: 89, symbol: "Ac", name: "Actinium", molarMass: 227, category: "actinide", period: 9, group: 4 },
  { atomicNumber: 90, symbol: "Th", name: "Thorium", molarMass: 232.038, category: "actinide", period: 9, group: 5 },
  { atomicNumber: 91, symbol: "Pa", name: "Protactinium", molarMass: 231.036, category: "actinide", period: 9, group: 6 },
  { atomicNumber: 92, symbol: "U", name: "Uranium", molarMass: 238.029, category: "actinide", period: 9, group: 7 },
  { atomicNumber: 93, symbol: "Np", name: "Neptunium", molarMass: 237, category: "actinide", period: 9, group: 8 },
  { atomicNumber: 94, symbol: "Pu", name: "Plutonium", molarMass: 244, category: "actinide", period: 9, group: 9 },
  { atomicNumber: 95, symbol: "Am", name: "Americium", molarMass: 243, category: "actinide", period: 9, group: 10 },
  { atomicNumber: 96, symbol: "Cm", name: "Curium", molarMass: 247, category: "actinide", period: 9, group: 11 },
  { atomicNumber: 97, symbol: "Bk", name: "Berkelium", molarMass: 247, category: "actinide", period: 9, group: 12 },
  { atomicNumber: 98, symbol: "Cf", name: "Californium", molarMass: 251, category: "actinide", period: 9, group: 13 },
  { atomicNumber: 99, symbol: "Es", name: "Einsteinium", molarMass: 252, category: "actinide", period: 9, group: 14 },
  { atomicNumber: 100, symbol: "Fm", name: "Fermium", molarMass: 257, category: "actinide", period: 9, group: 15 },
  { atomicNumber: 101, symbol: "Md", name: "Mendelevium", molarMass: 258, category: "actinide", period: 9, group: 16 },
  { atomicNumber: 102, symbol: "No", name: "Nobelium", molarMass: 259, category: "actinide", period: 9, group: 17 },
  { atomicNumber: 103, symbol: "Lr", name: "Lawrencium", molarMass: 266, category: "actinide", period: 9, group: 18 },
  { atomicNumber: 104, symbol: "Rf", name: "Rutherfordium", molarMass: 267, category: "transition metal", period: 7, group: 4 },
  { atomicNumber: 105, symbol: "Db", name: "Dubnium", molarMass: 268, category: "transition metal", period: 7, group: 5 },
  { atomicNumber: 106, symbol: "Sg", name: "Seaborgium", molarMass: 269, category: "transition metal", period: 7, group: 6 },
  { atomicNumber: 107, symbol: "Bh", name: "Bohrium", molarMass: 270, category: "transition metal", period: 7, group: 7 },
  { atomicNumber: 108, symbol: "Hs", name: "Hassium", molarMass: 277, category: "transition metal", period: 7, group: 8 },
  { atomicNumber: 109, symbol: "Mt", name: "Meitnerium", molarMass: 278, category: "transition metal", period: 7, group: 9 },
  { atomicNumber: 110, symbol: "Ds", name: "Darmstadtium", molarMass: 281, category: "transition metal", period: 7, group: 10 },
  { atomicNumber: 111, symbol: "Rg", name: "Roentgenium", molarMass: 282, category: "transition metal", period: 7, group: 11 },
  { atomicNumber: 112, symbol: "Cn", name: "Copernicium", molarMass: 285, category: "transition metal", period: 7, group: 12 },
  { atomicNumber: 113, symbol: "Nh", name: "Nihonium", molarMass: 286, category: "post-transition metal", period: 7, group: 13 },
  { atomicNumber: 114, symbol: "Fl", name: "Flerovium", molarMass: 289, category: "post-transition metal", period: 7, group: 14 },
  { atomicNumber: 115, symbol: "Mc", name: "Moscovium", molarMass: 290, category: "post-transition metal", period: 7, group: 15 },
  { atomicNumber: 116, symbol: "Lv", name: "Livermorium", molarMass: 293, category: "post-transition metal", period: 7, group: 16 },
  { atomicNumber: 117, symbol: "Ts", name: "Tennessine", molarMass: 294, category: "metalloid", period: 7, group: 17 },
  { atomicNumber: 118, symbol: "Og", name: "Oganesson", molarMass: 294, category: "noble gas", period: 7, group: 18 },
];
